### ISSUE TITLE
Stay authenticated

### ISSUE THREAD

**Issue by Tiebe** [wouter173/zermelo.py#4]
If I enter an access code, I believe it's only valid for 16 hours. Is it possible to automatically re-authenticate so I don't have to enter a code every 16 hours?

Thank you in advance,

Tiebe

**Comment by JXRIS** [comment]
^ Also interested in this. Would love some help.

**Comment by J0eppp** [comment]
I'm not sure if you still need this info. 
The token that is retrieved from Zermelo is only valid for 16 hours. This cannot be changed and the token cannot be refreshed. 
You'll need a new code to get a new access code. 
I've contacted Zermelo to ask if something like a refresh code could be implemented. 
I'll follow up on this once I know more.

**Comment by J0eppp** [comment]
Update: the code is valid for 10 years and you cannot refresh this code. That is not necessary however because 10 years seems plenty of time. 
When you request info about this token it says that it is only valid for 16 hours but that is incorrect. 

*PS. I think this issue can be closed.*

**Comment by saerio** [comment]
hi, it seems as of now the code is changing every time the connect external app button is pressed and is invalidated upon usage. i think it can be re-opened
